/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedFunnelRouteImport } from './routes/_authenticated/funnel'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedSettingsPreferencesRouteImport } from './routes/_authenticated/settings.preferences'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as AuthenticatedReportsIdRouteImport } from './routes/_authenticated/reports.$id'
import { Route as ApiPublicReportsWeeklySummaryRouteImport } from './routes/api/public/reports/weekly-summary'
import { Route as ApiPublicMetaSyncRouteImport } from './routes/api/public/meta/sync'
import { Route as ApiPublicMetaCallbackRouteImport } from './routes/api/public/meta/callback'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunnelRoute = AuthenticatedFunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsPreferencesRoute =
  AuthenticatedSettingsPreferencesRouteImport.update({
    id: '/settings/preferences',
    path: '/settings/preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIdRoute = AuthenticatedReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedReportsRoute,
} as any)
const ApiPublicReportsWeeklySummaryRoute =
  ApiPublicReportsWeeklySummaryRouteImport.update({
    id: '/api/public/reports/weekly-summary',
    path: '/api/public/reports/weekly-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaSyncRoute = ApiPublicMetaSyncRouteImport.update({
  id: '/api/public/meta/sync',
  path: '/api/public/meta/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaCallbackRoute = ApiPublicMetaCallbackRouteImport.update({
  id: '/api/public/meta/callback',
  path: '/api/public/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funnel': typeof AuthenticatedFunnelRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/r/$token': typeof RTokenRoute
  '/reports/$id': typeof AuthenticatedReportsIdRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
  '/api/public/meta/sync': typeof ApiPublicMetaSyncRoute
  '/api/public/reports/weekly-summary': typeof ApiPublicReportsWeeklySummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/funnel': typeof AuthenticatedFunnelRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/r/$token': typeof RTokenRoute
  '/reports/$id': typeof AuthenticatedReportsIdRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
  '/api/public/meta/sync': typeof ApiPublicMetaSyncRoute
  '/api/public/reports/weekly-summary': typeof ApiPublicReportsWeeklySummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/funnel': typeof AuthenticatedFunnelRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/r/$token': typeof RTokenRoute
  '/_authenticated/reports/$id': typeof AuthenticatedReportsIdRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
  '/api/public/meta/sync': typeof ApiPublicMetaSyncRoute
  '/api/public/reports/weekly-summary': typeof ApiPublicReportsWeeklySummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/admin'
    | '/campaigns'
    | '/dashboard'
    | '/funnel'
    | '/insights'
    | '/onboarding'
    | '/reports'
    | '/r/$token'
    | '/reports/$id'
    | '/settings/integrations'
    | '/settings/preferences'
    | '/settings/users'
    | '/reports/'
    | '/api/public/meta/callback'
    | '/api/public/meta/sync'
    | '/api/public/reports/weekly-summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/admin'
    | '/campaigns'
    | '/dashboard'
    | '/funnel'
    | '/insights'
    | '/onboarding'
    | '/r/$token'
    | '/reports/$id'
    | '/settings/integrations'
    | '/settings/preferences'
    | '/settings/users'
    | '/reports'
    | '/api/public/meta/callback'
    | '/api/public/meta/sync'
    | '/api/public/reports/weekly-summary'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/_authenticated/admin'
    | '/_authenticated/campaigns'
    | '/_authenticated/dashboard'
    | '/_authenticated/funnel'
    | '/_authenticated/insights'
    | '/_authenticated/onboarding'
    | '/_authenticated/reports'
    | '/r/$token'
    | '/_authenticated/reports/$id'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/preferences'
    | '/_authenticated/settings/users'
    | '/_authenticated/reports/'
    | '/api/public/meta/callback'
    | '/api/public/meta/sync'
    | '/api/public/reports/weekly-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicMetaCallbackRoute: typeof ApiPublicMetaCallbackRoute
  ApiPublicMetaSyncRoute: typeof ApiPublicMetaSyncRoute
  ApiPublicReportsWeeklySummaryRoute: typeof ApiPublicReportsWeeklySummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funnel': {
      id: '/_authenticated/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof AuthenticatedFunnelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/preferences': {
      id: '/_authenticated/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$id': {
      id: '/_authenticated/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AuthenticatedReportsIdRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/api/public/reports/weekly-summary': {
      id: '/api/public/reports/weekly-summary'
      path: '/api/public/reports/weekly-summary'
      fullPath: '/api/public/reports/weekly-summary'
      preLoaderRoute: typeof ApiPublicReportsWeeklySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/sync': {
      id: '/api/public/meta/sync'
      path: '/api/public/meta/sync'
      fullPath: '/api/public/meta/sync'
      preLoaderRoute: typeof ApiPublicMetaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/callback': {
      id: '/api/public/meta/callback'
      path: '/api/public/meta/callback'
      fullPath: '/api/public/meta/callback'
      preLoaderRoute: typeof ApiPublicMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsIdRoute: typeof AuthenticatedReportsIdRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsIdRoute: AuthenticatedReportsIdRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFunnelRoute: typeof AuthenticatedFunnelRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsPreferencesRoute: typeof AuthenticatedSettingsPreferencesRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFunnelRoute: AuthenticatedFunnelRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsPreferencesRoute: AuthenticatedSettingsPreferencesRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicMetaCallbackRoute: ApiPublicMetaCallbackRoute,
  ApiPublicMetaSyncRoute: ApiPublicMetaSyncRoute,
  ApiPublicReportsWeeklySummaryRoute: ApiPublicReportsWeeklySummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
